# Generated by Django 2.2.17 on 2020-12-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='user_details',
        ),
    ]
